version: '3.1'
services:
  leetcode:
    container_name: leetcode
    build:
      dockerfile: Dockerfile
      context: .
    env_file: .env
    ports:
      - "3000:3000"
    restart: on-failure
    volumes:
      - leetcode:/usr/src/app/
    networks:
      - main
volumes:
  leetcode:

networks:
  main:
    external: true