name: Deploy

on:
  push:
    tags: releases/[1-9]+.[0-9]+.[0-9]+
    branches: mrbelka12000-patch-3
jobs:
  production:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://pumping-leetcode.kz
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIV_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PUB_KEY }}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa.pub
          ssh-keyscan -H ${{ secrets.IP }} >> ~/.ssh/known_hosts
      - name: copy builds to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USER_IP }} "cd leetcode_tournament/ && git pull && docker compose up --build -d && exit"